Repository TIS2023-FMFI/pracovne-cesty, pull requests merged in 2024-02, with the labels that each got.

#82 Permissions and auth middlewares
  src/app/Enums/UserType.php
  src/app/Http/Controllers/SynchronizationController.php
  src/app/Http/Kernel.php
  src/app/Models/User.php
  src/app/Providers/RouteServiceProvider.php
  src/composer.json
  src/composer.lock
  src/config/permission.php
  src/database/migrations/2023_12_12_215925_create_users_table.php
  src/database/migrations/2024_01_28_012937_create_permission_tables.php
  src/database/seeders/DatabaseSeeder.php
  src/database/seeders/RoleAndPermissionSeeder.php
  src/database/seeders/UserSeeder.php
  src/routes/web.php
Labels: major component

#85 Spp controller
  src/app/Http/Controllers/SPPController.php
  src/database/migrations/2023_12_14_230033_create_spp_symbols_table.php
  src/resources/views/business-trips/edit.blade.php
  src/resources/views/components/modals/add-user.blade.php
  src/resources/views/spp/manage.blade.php
Labels: major component

#88 Javascript and frontend fixes
  src/resources/views/business-trips/create.blade.php
  src/resources/views/business-trips/edit.blade.php
  src/resources/views/components/document-export-icon.blade.php
  src/resources/views/components/dropdown-input.blade.php
  src/resources/views/components/simple-input.blade.php
  src/resources/views/components/textarea.blade.php
  src/resources/views/users/register.blade.php
Labels: enhancement

#90 Invitation link redirect to registration
  src/app/Enums/UserType.php
  src/app/Http/Controllers/UserController.php
  src/app/Models/InvitationLink.php
  src/routes/web.php
Labels: enhancement

#91 User based frontend
  src/resources/views/business-trips/create.blade.php
  src/resources/views/business-trips/edit.blade.php
  src/resources/views/components/layout.blade.php
  src/resources/views/dashboard.blade.php
Labels: bug, enhancement

#92 Misc minor fixes
  src/app/Http/Controllers/UserController.php
  src/app/Models/InvitationLink.php
  src/config/app.php
  src/database/factories/InvitationLinkFactory.php
  src/database/factories/UserFactory.php
  src/database/migrations/2023_12_14_213431_create_expenses_table.php
  src/database/seeders/DatabaseSeeder.php
  src/database/seeders/InvitationLinkSeeder.php
Labels: enhancement

#93 Misc minor fixes
  src/app/Http/Controllers/UserController.php
  src/database/migrations/2023_12_12_190719_create_business_trips_table.php
  src/routes/web.php
Labels: enhancement

#64 BusinessTripController
  src/app/Http/Controllers/BusinessTripController.php
  src/app/Http/Controllers/Controller.php
  src/app/Models/BusinessTrip.php
  src/app/Models/ConferenceFee.php
  src/app/Models/Expense.php
  src/app/Models/Reimbursement.php
  src/app/Models/TripContribution.php
  src/database/factories/BusinessTripFactory.php
  src/database/migrations/2023_12_12_190719_create_business_trips_table.php
  src/resources/views/business-trips/create.blade.php
  src/resources/views/business-trips/edit.blade.php
  src/routes/web.php
Labels: major component

#94 routing and linking fixes
  src/app/Http/Controllers/BusinessTripController.php
  src/resources/views/components/content-item.blade.php
  src/resources/views/components/document-export-icon.blade.php
  src/routes/web.php
Labels: bug

#95 Form fixes
  src/app/Http/Controllers/UserController.php
  src/database/migrations/2023_12_12_215925_create_users_table.php
  src/resources/views/business-trips/edit.blade.php
  src/resources/views/components/content-section.blade.php
  src/resources/views/components/modals/add-user.blade.php
  src/resources/views/users/register.blade.php
Labels: bug

#97 PDF export test and debug
  src/app/Http/Controllers/BusinessTripController.php
  src/public/DejaVuSans.ttf
Labels: bug

#99 User management testing and debug
  src/app/Http/Controllers/BusinessTripController.php
  src/app/Http/Controllers/UserController.php
  src/app/View/Components/SimpleInput.php
  src/database/migrations/2023_12_12_190719_create_business_trips_table.php
  src/resources/views/components/simple-input.blade.php
  src/resources/views/users/register.blade.php
Labels: bug

#101 Minor changes to `invite` method
  src/app/Http/Controllers/UserController.php
Labels: enhancement

#109 Styling
  src/app/View/Components/SimpleInput.php
  src/public/css/style.css
  src/resources/views/business-trips/create.blade.php
  src/resources/views/components/button.blade.php
  src/resources/views/components/flash-message.blade.php
  src/resources/views/components/layout.blade.php
  src/resources/views/components/modal.blade.php
  src/resources/views/components/modals/add-user.blade.php
  src/resources/views/components/modals/forgot-password.blade.php
  src/resources/views/components/simple-input.blade.php
  src/resources/views/dashboard.blade.php
  src/resources/views/reset-password.blade.php
  src/resources/views/spp/manage.blade.php
Labels: major component

#107 Password reset
  src/app/Http/Controllers/BusinessTripController.php
  src/app/Http/Controllers/UserController.php
  src/app/Models/User.php
  src/database/migrations/2024_02_08_205529_create_password_reset_tokens_table.php
  src/resources/views/components/modals/forgot-password.blade.php
  src/resources/views/reset-password.blade.php
  src/routes/web.php
Labels: major component

#100 Error messages
  src/app/Http/Controllers/BusinessTripController.php
  src/app/Http/Controllers/SPPController.php
  src/app/Http/Controllers/UserController.php
  src/composer.json
  src/composer.lock
  src/config/app.php
  src/lang/en.json
  src/lang/en/actions.php
  src/lang/en/auth.php
  src/lang/en/http-statuses.php
  src/lang/en/pagination.php
  src/lang/en/passwords.php
  src/lang/en/validation.php
  src/lang/sk.json
  src/lang/sk/actions.php
  src/lang/sk/auth.php
  src/lang/sk/http-statuses.php
  src/lang/sk/pagination.php
  src/lang/sk/passwords.php
  src/lang/sk/validation.php
  src/resources/views/emails/cancellation_user.blade.php
  src/resources/views/emails/cancellation_user_text.blade.php
  src/resources/views/emails/documents_signing_user.blade.php
  src/resources/views/emails/documents_signing_user_text.blade.php
  src/resources/views/emails/new_note_admin.blade.php
  src/resources/views/emails/new_note_admin_text.blade.php
  src/resources/views/emails/new_trip_admin.blade.php
  src/resources/views/emails/new_trip_admin_text.blade.php
  src/resources/views/emails/registration_externist.blade.php
  src/resources/views/emails/registration_externist_text.blade.php
  src/resources/views/emails/registration_student.blade.php
  src/resources/views/emails/registration_student_text.blade.php
  src/resources/views/emails/report_signing_user.blade.php
  src/resources/views/emails/report_signing_user_text.blade.php
Labels: enhancement

#114 Pritomnost connector testing and debug
  src/app/Http/Controllers/BusinessTripController.php
  src/app/Http/Controllers/SynchronizationController.php
  src/app/Http/Controllers/UserController.php
Labels: bug

#111 meals table addition
  src/app/Enums/TripState.php
  src/app/Http/Controllers/BusinessTripController.php
  src/resources/views/business-trips/edit.blade.php
Labels: enhancement

#113 admin-create
  src/app/Http/Controllers/BusinessTripController.php
  src/resources/views/business-trips/create.blade.php
  src/resources/views/dashboard.blade.php
Labels: major component

#117 Responsive styling
  src/app/Enums/TripState.php
  src/app/Http/Controllers/BusinessTripController.php
  src/app/Http/Controllers/UserController.php
  src/app/View/Components/ContentItem.php
  src/public/css/style.css
  src/public/images/favicon.ico
  src/resources/views/business-trips/create.blade.php
  src/resources/views/business-trips/edit.blade.php
  src/resources/views/components/button.blade.php
  src/resources/views/components/flash-message.blade.php
  src/resources/views/components/layout.blade.php
  src/resources/views/components/link-button.blade.php
  src/resources/views/components/overview-item.blade.php
  src/resources/views/components/state-icon.blade.php
  src/resources/views/components/trip-list-item.blade.php
  src/resources/views/dashboard.blade.php
  src/resources/views/spp/manage.blade.php
Labels: enhancement

#119 Form sectioning
  src/app/Http/Controllers/BusinessTripController.php
  src/lang/sk/validation.php
  src/resources/views/business-trips/create.blade.php
  src/resources/views/business-trips/edit.blade.php
Labels: enhancement

#121 Spp fixes
  src/app/Http/Controllers/BusinessTripController.php
  src/database/factories/SppSymbolFactory.php
  src/database/migrations/2023_12_14_230033_create_spp_symbols_table.php
  src/database/seeders/SppSymbolSeeder.php
  src/database/seeders/TripPurposeSeeder.php
  src/resources/views/business-trips/create.blade.php
  src/resources/views/business-trips/edit.blade.php
Labels: enhancement

#122 Misc minor fixes
  src/app/Http/Controllers/BusinessTripController.php
  src/app/Http/Controllers/SynchronizationController.php
  src/app/Models/PritomnostAbsence.php
  src/app/Models/User.php
  src/app/Policies/BusinessTripPolicy.php
  src/database/seeders/StaffSeeder.php
  src/routes/web.php
Labels: enhancement

#123 excluded non-external users from password reset
  src/app/Http/Controllers/UserController.php
Labels: enhancement

#124 fixed spp frontend and controller
  src/app/Http/Controllers/SPPController.php
  src/resources/views/spp/manage.blade.php
Labels: bug

#120 fixes to pdf fields
  src/resources/views/business-trips/edit.blade.php
  src/storage/app/pdf_templates/cestne_vyhlasenie_k_zahranicnej_pc.pdf
  src/storage/app/pdf_templates/dohoda_o_poskytnuti_cestovnych_nahrad.pdf
  src/storage/app/pdf_templates/kontrolny_list.pdf
  src/storage/app/pdf_templates/platobny_prikaz.pdf
  src/storage/app/pdf_templates/sprava_z_tuzemskej_pc.pdf
  src/storage/app/pdf_templates/sprava_zo_zahranicnej_pc.pdf
Labels: bug

#125 Pdf fixes
  src/app/Http/Controllers/BusinessTripController.php
  src/resources/views/business-trips/edit.blade.php
  src/resources/views/emails/cancellation_user.blade.php
  src/resources/views/emails/cancellation_user_text.blade.php
  src/resources/views/emails/documents_signing_user.blade.php
  src/resources/views/emails/documents_signing_user_text.blade.php
  src/resources/views/emails/registration_externist.blade.php
  src/resources/views/emails/registration_externist_text.blade.php
  src/resources/views/emails/report_signing_user.blade.php
  src/resources/views/emails/report_signing_user_text.blade.php
Labels: bug

#127 Route fixes
  src/resources/views/business-trips/create.blade.php
  src/resources/views/business-trips/edit.blade.php
  src/resources/views/components/document-export-icon.blade.php
  src/resources/views/components/layout.blade.php
  src/resources/views/components/modal.blade.php
  src/resources/views/components/modals/add-user.blade.php
  src/resources/views/components/modals/forgot-password.blade.php
  src/resources/views/components/trip-list-item.blade.php
  src/resources/views/dashboard.blade.php
  src/resources/views/reset-password.blade.php
  src/resources/views/spp/manage.blade.php
  src/resources/views/users/register.blade.php
Labels: bug

#128 Minor route fixes
  src/app/Providers/RouteServiceProvider.php
  src/public/css/style.css
  src/routes/web.php
Labels: bug

#129 Pritomnost transactions
  src/app/Http/Controllers/BusinessTripController.php
  src/app/Http/Controllers/SynchronizationController.php
  src/config/app.php
  src/database/seeders/DatabaseSeeder.php
Labels: enhancement

#130 Fix name for Pritomnost DB
  src/app/Http/Controllers/SynchronizationController.php
  src/config/database.php
Labels: bug

#131 Update README
  README.md
  src/database/seeders/DatabaseSeeder.php
Labels: documentation

#132 added docs
  docs/gui_frames/admin-add-user.pdf
  docs/gui_frames/admin-logged-in-homepage.pdf
  docs/gui_frames/admin-report-detail.pdf
  docs/gui_frames/admin-spp.pdf
  docs/gui_frames/admin-trip-detail.pdf
  docs/gui_frames/forgotten-password.pdf
  docs/gui_frames/logged-out-homepage.pdf
  docs/gui_frames/user-add-new-trip-warning.pdf
  docs/gui_frames/user-add-new-trip.pdf
  docs/gui_frames/user-add-report.pdf
  docs/gui_frames/user-logged-in-homepage.pdf
  docs/gui_frames/user-registration.pdf
  docs/gui_frames/user-trip-detail.pdf
  docs/images/class_diagram.png
  docs/technicka_dokumentacia.pdf
Labels: documentation

#133 Last fixes
  src/app/Enums/TripState.php
  src/app/Http/Controllers/BusinessTripController.php
  src/app/View/Components/DropdownInput.php
  src/app/View/Components/Textarea.php
  src/public/css/style.css
  src/resources/views/business-trips/edit.blade.php
  src/resources/views/components/dropdown-input.blade.php
  src/resources/views/components/layout.blade.php
  src/resources/views/components/modals/add-user.blade.php
  src/resources/views/components/textarea.blade.php
Labels: bug
